name: Deploy Symfony Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Caddyfile with production version
        run: |
          echo "Replacing frankenphp/Caddyfile with frankenphp/Caddyfile_prod..."
          mv frankenphp/Caddyfile_prod frankenphp/Caddyfile
          cat frankenphp/Caddyfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: erikweidenauer
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: frankenphp_prod
          push: true
          tags: erikweidenauer/onlydance-ar-symfony:latest

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: onlydance.at
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Pulling latest PHP image..."
            docker pull erikweidenauer/onlydance-ar-symfony:latest

            echo "Deploying stack..."
            docker compose -f compose.yaml down
            docker compose -f compose.yaml up -d
            docker exec -it administrator-php-1 bin/console createAdmin

            echo "Cleaning up old images..."
            docker image prune -f
